---
abstract: 'Make your attribute(s) tolerant to undef initialization'
author:
  - 'Cory G Watson <gphat at cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.002
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-UndefTolerant
requires:
  Moose: 0.89
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-UndefTolerant
  repository: git://git.moose.perl.org/MooseX-UndefTolerant.git
version: 0.10
